fix benchmark GeluBackward
NVIDIA/Fuser pull request #102
Opened 2023-03-30 17:38 UTC by liqiangxl

same as https://github.com/NVIDIA/Fuser/issues/96 and https://github.com/NVIDIA/Fuser/pull/100

2023-03-30 19:03 UTC, zasdfgbnm approved these changes

2023-03-30 22:01 UTC, jjsjann123 commented
!build

2023-03-30 22:03 UTC, jjsjann123 requested changes
No changes needed, I'm just blocking the merge!
:smiling_imp:

2023-03-31 16:19 UTC, jjsjann123 approved these changes
sorry for hijacking your PR.
Feel free to merge it now (and please ignore the failing blossom CI runs)

2023-03-31 16:50 UTC, merged