Ensure that non-matmul schedulers reject matmul fusions
NVIDIA/Fuser pull request #2262
Opened 2024-05-16 17:14 UTC by jacobhinkle

This ensures that if MmaOp or MatmulOp occur in the fusion, only ExprEval or Matmul schedulers will consider it.

2024-05-16 17:15 UTC, jacobhinkle commented
Included test fails on main

2024-05-17 14:19 UTC, jacobhinkle commented on tests/cpp/test_matmul_scheduler.cpp
> +// at least one enabled).
A version of this test that works like this TODO suggests is here (passing on that branch): https://github.com/NVIDIA/Fuser/pull/2236/files#diff-79605590906bd352b3f5d8798d0f16a00350ab8e740cdc0e64a89a7f8b34d204R341-R351

2024-05-17 19:34 UTC, Priya2698 requested changes

2024-05-17 19:34 UTC, Priya2698 commented on tests/cpp/test_matmul_scheduler.cpp
> +      "matmul fusion must have at least one MmaOp");
nit: Easier to read with the value as rhs
```Suggestion
  NVF_CHECK(
      ir_utils::getOpsOfType<MatmulOp>(fusion.get()).size() == 1,
      "matmul fusion must have at least one matmul op.");
```

2024-05-17 19:34 UTC, Priya2698 commented on tests/cpp/test_matmul_scheduler.cpp
> +  NVF_CHECK(outputs[0].allclose(tref, 0.001, 0.001));
We can use `testValidate` here, to avoid setting tolerance values.

2024-05-17 19:34 UTC, Priya2698 commented on csrc/ir/utils.cpp
> +  return hasOpsOfType<MmaOp, MatmulOp>(fusion);
We can add `LinearOp` here now.

2024-05-20 17:44 UTC, Priya2698 approved these changes
LGTM.

2024-05-20 18:27 UTC, jacobhinkle commented
!build

2024-05-20 21:56 UTC, merged