Assert that trie_node_ != nullptr in some fd methods
NVIDIA/Fuser pull request #2442
Opened 2024-06-23 13:08 UTC by jacobhinkle

Fixes #2430 since we _should_ error here but we _should not_ segfault ever.

2024-06-23 13:08 UTC, jacobhinkle commented
!build

2024-06-24 17:23 UTC, kevinstephano requested changes
I just wanted the error messages to be clearer for users.

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      "defineScalar must be called inside a 'with' block");
```suggestion
      "define_scalar() must be called from an initialized definition via a python context manager or a child class' definition() method.");
```

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      trie_node_ != nullptr, "AddTensor must be called inside a 'with' block");
```suggestion
      trie_node_ != nullptr, "addTensor() must be called from an initialized definition via a python context manager or a child class' definition() method.");
```

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      "defineTensor must be called inside a 'with' block");
```suggestion
      "define_tensor() must be called from an initialized definition via a python context manager or a child class' definition() method.");
```

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      "defineVector must be called inside a 'with' block");
```suggestion
      "define_vector() must be called from an initialized definition via a python context manager or a child class' definition() method.");
```

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      "defineRecord must be called inside a 'with' block");
```suggestion
      "defineRecord() must be called from an initialized definition via a python context manager or a child class' definition() method.");
```

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      "defineScalar must be called inside a 'with' block");
Note, I am purposely suggesting using the python function name `define_scalar()` to give a better error message given this error is most likely to be seen from Python.

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      trie_node_ != nullptr, "AddTensor must be called inside a 'with' block");
I don't think this method is actually exposed via python but it doesn't hurt to add the check.

2024-06-24 17:23 UTC, kevinstephano commented on csrc/python_frontend/fusion_definition.cpp
> +      "defineRecord must be called inside a 'with' block");
I don't think this method is actually exposed via python but it doesn't hurt to add the check.

2024-06-24 17:37 UTC, kevinstephano approved these changes
LGTM!

2024-06-25 12:32 UTC, merged